<?php

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__)
    ->exclude([
        'autogenerated_content',
        'tests/fixtures',
    ])
;

return (new PhpCsFixer\Config())
    ->setRules([
        '@PSR12' => true,
        'align_multiline_comment' =>  ['comment_type' => 'all_multiline'],
        'phpdoc_align' => ['align' => 'left'],
        'concat_space' => ['spacing' => 'one'],
        'return_type_declaration' => ['space_before' => 'none']
    ])
    ->setFinder($finder)
    ->setUsingCache(false);
// ->setIndent("    ")
// ->setLineEnding("\r\n")
;
