<?php

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__)
    ->exclude([
        'autogenerated_content',
        'tests/fixtures',
    ])
;

return (new PhpCsFixer\Config())
    ->setRules([
        '@PSR12' => true,
        'align_multiline_comment' =>  ['comment_type' => 'all_multiline'],
        'phpdoc_align' => ['align' => 'left'],
    ])
    ->setFinder($finder)
    ->setUsingCache(false);
// ->setIndent("    ")
// ->setLineEnding("\r\n")
;
